# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: DoWhy CI

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        poetry-version: [1.2.0]
        test-group: [1, 2, 3, 4]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry ${{ matrix.poetry-version }}
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install graphviz
        run: |
          sudo apt install graphviz libgraphviz-dev graphviz-dev pkg-config

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "installing poetry dependencies"
          poetry install -E plotting -E causalml

      - name: Run Advanced Tests
        run: poetry run poe test_advanced --splits 4 --group ${{ matrix.test-group }}
